services:
    web:
        image: nginx:latest
        container_name: wordpress_ilashes_webserver
        ports:
            - "8080:80"
        volumes:
            - ./application:/var/www/html
            - ./webserver/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - "php-fpm"
    php-fpm:
        build:
            context: '.'
            dockerfile: "Dockerfile"
        container_name: wordpress_ilashes_php
        volumes:
            - ./application:/var/www/html
    db:
        image: mysql:8
        container_name: wordpress_ilashes_db
        volumes:
          - ./mysql:/var/lib/mysql
        restart: always
        tty: true
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ilashes
          MYSQL_USER: webgator
          MYSQL_PASSWORD: webgator
    redis:
        image: redis:6.0.16-alpine
        container_name: wordpress_ilashes_redis
        command: redis-server --requirepass secret
        ports:
          - "6379:6379"
        volumes:
          - ./redis:/data
